First simulate a lossy transmission then add parity bits to detect errors in the transmission

In [12]:
using Random
using Distributions

In [110]:
rng = MersenneTwister(1234)
input = bitrand(rng,99)
@show input

input = Bool[0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1]


99-element BitVector:
 0
 0
 1
 1
 0
 1
 1
 1
 0
 0
 0
 0
 1
 ⋮
 0
 0
 1
 0
 0
 1
 0
 1
 0
 1
 0
 1

In [111]:
b = 99/3
b += 99
d = zeros(132)
par_sum = 0
count = 0
iter = 1
for i in input
    d[iter] = i
    count += 1
    par_sum += i
    if count%3 == 0
        iter += 1
        par = par_sum%2
        par_sum = 0
        d[iter] = par
        count = 0
    end
    iter += 1
end

#correctly adds a even parity bit after 3 bits
@show input
@show d

input = Bool[0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1]
d = [0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0]


132-element Vector{Float64}:
 0.0
 0.0
 1.0
 1.0
 1.0
 0.0
 1.0
 0.0
 1.0
 1.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 1.0
 1.0
 0.0
 1.0
 0.0
 1.0
 1.0
 0.0
 1.0
 0.0

In [112]:
# now add noise to signal
sent = zeros(length(d))
for i in 1:length(d)
    if d[i] == 0
        sent[i] = -1
    else
        sent[i] = 1
    end
end

@show sent

sent = [-1.0, -1.0, 1.0, 1.0, 1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, -1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1.0, -1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, -1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0]


132-element Vector{Float64}:
 -1.0
 -1.0
  1.0
  1.0
  1.0
 -1.0
  1.0
 -1.0
  1.0
  1.0
 -1.0
 -1.0
 -1.0
  ⋮
 -1.0
 -1.0
  1.0
  1.0
 -1.0
  1.0
 -1.0
  1.0
  1.0
 -1.0
  1.0
 -1.0

In [121]:
#this isnt working too nicely
b = rand(Uniform(-1,1),132)
SNR = -8
sigma = 1/sqrt(10^(SNR/10)*2)
#make a term for the snr
b = b*sigma
sent = sent+b


#@show sent
# if rand number < 0.1 toggle bit

132-element Vector{Float64}:
  0.05215571163613486
 -2.475904237328928
  0.154374299061995
  0.8415285242515349
 -0.8590156668620809
 -1.7084113466889816
  2.2184506057155695
 -0.22728604529208501
 -0.3212981234794021
  1.8422012794681204
 -1.0885171523607375
 -1.678372001480624
  0.869509288790846
  ⋮
 -1.9599498656862893
 -2.060261030732086
  1.8435489185020082
  0.32063278440862086
 -1.1715898964827443
 -1.0176983889515956
 -0.44883418546445286
 -0.1433938577744598
  2.2103429681561284
 -0.6464291869217148
  0.7783804202586061
  0.4849306222014105

In [1]:
prob_bit_err = 0.1
if rand() < prob_bit_error
    #sent toggle suit

0.8541430488338433

In [122]:
# now demod and make a decision
rec = zeros(length(sent))

for i in 1:length(sent)
    if sent[i]>0
        rec[i] = 1
    else
        rec[i] = 0
    end
end

@show d
@show rec

d = [0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0]
rec = [1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0

132-element Vector{Float64}:
 1.0
 0.0
 1.0
 1.0
 0.0
 0.0
 1.0
 0.0
 0.0
 1.0
 0.0
 0.0
 1.0
 ⋮
 0.0
 0.0
 1.0
 1.0
 0.0
 0.0
 0.0
 0.0
 1.0
 0.0
 1.0
 1.0

In [123]:
#differences between sent and recieved now for decoding
count = 0
for i in 1:length(rec)
    if rec[i]!=d[i]
        count+=1
    end
end
print(count)


29

In [124]:
# need to remove parity bit and say if theres an error in the codeword
output = zeros(99)
par_count = 0 

for i in 1:length(rec)
    if i%4 == 0
        par_count+=1
    else
        output[i-par_count] = rec[i]
    end
  
end



@show par_count

@show output
@show input


par_count = 33
output = [1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0]
input = Bool[0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1]


99-element BitVector:
 0
 0
 1
 1
 0
 1
 1
 1
 0
 0
 0
 0
 1
 ⋮
 0
 0
 1
 0
 0
 1
 0
 1
 0
 1
 0
 1

In [125]:
#count errors
errors = 0

for i in 1:length(output)
    if output[i] != input[i]
        errors+=1
    end
end

parity_bit_errors = count-errors
@show errors
@show parity_bit_errors

errors = 21
parity_bit_errors = 8


8

In [126]:
# now to see if the parity bits correctly find the errors
# code words 0 means no error, 1 means error but parity check detected it,2 means no error but parity bit
# detected an error, 3 means error but its undetected
its = 99/3
actual_err = zeros(33)
numoferrors = zeros(33)
inarr = zeros(4)
outarr = zeros(4)
checksum = 0
for i in 1:its
    p = (i-1)*4+1
    p = Int(p)
    inarr= d[p:p+3]
    outarr = rec[p:p+3]
    if inarr != outarr
        actual_err[Int(i)] = 1
    end
    for r in 1:4
        checksum += outarr[r]
        if r%4 == 0
            if checksum %2 != 0
                numoferrors[Int(i)]=1
            end
            checksum = 0
        end
            
    end
    #print(inarr)
    #print(outarr)
end

@show actual_err
@show numoferrors

actual_err = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0]
numoferrors = [1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0]


33-element Vector{Float64}:
 1.0
 1.0
 1.0
 0.0
 0.0
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0
 1.0
 1.0
 ⋮
 1.0
 1.0
 1.0
 0.0
 0.0
 1.0
 0.0
 0.0
 1.0
 0.0
 0.0
 1.0

In [127]:
# i will go 1 2 3 4 5 6
# want 1 5 9 13 
# relation = (i-1)*4+1

In [135]:
# now remove parity bits and see how many of the actual message bits were detected correctly,incorrectly or missed
output_bits =zeros(99)
count = 0
for i in 1:length(rec)
    if i%4 == 0
        count+=1
    else
        output_bits[i-count] = rec[i]
    end
end

@show rec
@show output_bits

rec = [1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0]
output_bits = [1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0

99-element Vector{Float64}:
 1.0
 0.0
 1.0
 0.0
 0.0
 1.0
 0.0
 1.0
 0.0
 1.0
 0.0
 0.0
 1.0
 ⋮
 0.0
 0.0
 1.0
 0.0
 0.0
 1.0
 0.0
 0.0
 0.0
 1.0
 0.0
 1.0

In [128]:
# now know locations of detected errors
# and locations of actual errors
detected = 0
undetected = 0
wrong_err = 0


for i in 1:length(actual_err)
    if actual_err[i] == 1 && numoferrors[i] == 1
        detected += 1
    end
    
    if actual_err[i] == 1 && numoferrors[i] == 0
        undetected += 1
    end
    
    if actual_err[i] == 0 && numoferrors[i] == 1
        wrong_err += 1
    end
end
    
    
@show detected
@show undetected
@show wrong_err

detected = 17
undetected = 6
wrong_err = 0


0

In [134]:
# so nows i have the output message bits and the locations of the errors so lets group them in threes and see
# how how many errors were correctly handled
# first some code words
# 00 means the output message matches the input message and no error
# 10 out==in and error
# 01 means out!=in and no error
# 11 out!=in and error detected


# i will go 1 2 3 4 5 6
# want 1 4 7 10 
# relation = (i-1)*3+1

in1 = zeros(3)
out1 = zeros(3)


for i in 1:length(33)
    l = 0
    q = (i-1)*3+1
    Int(q)
    in1 = input[q:q+2]
    out1 = output_bits[q:q+2]
    if in1 != out1
        l+=1
    end
    if 
end
